;
; File generated by cc65 v 2.19 - Git 7165b29
;
	.fopt		compiler,"cc65 v 2.19 - Git 7165b29"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	jsr     pushax
	jmp     L0006
L0002:	ldx     #$00
	lda     #$41
	sta     $A000
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0005:	ldy     #$01
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvc     L0009
	eor     #$80
L0009:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0008
	jmp     L0006
L0008:	ldx     #$00
	lda     #$42
	sta     $A001
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0005
L0006:	jmp     L0002
	jmp     L0001
L0001:	jsr     incsp2
	rts

.endproc

