;
; File generated by cc65 v 2.19 - Git 7165b29
;
	.fopt		compiler,"cc65 v 2.19 - Git 7165b29"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$46
	jsr     pusha
	ldx     #$00
	lda     #$41
	sta     $A000
	ldx     #$00
	lda     #$42
	sta     $A001
	ldx     #$00
	lda     #$43
	sta     $A002
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldx     #$A0
	lda     #$03
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$44
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldx     #$A0
	lda     #$03
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$4E
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0002:	jmp     L0002
	jmp     L0001
L0001:	jsr     incsp3
	rts

.endproc

